services:
  redis:
    image: "redis:alpine"
    container_name: "spelldraw-redis"
    command: --port 9000
    ports:
      - "9000:9000"
    expose:
      - 9000
  server:
    container_name: "spelldraw-server"
    build:
      context: .
      target: base
    command: npm run dev
    depends_on:
      - redis
    environment:
      - LOG_LEVEL=DEBUG
      - PORT=3000
      - DATABASE_URL=redis://redis:9000
    ports:
      - "3000:3000"
